import { defineStore } from 'pinia'
import axios from 'axios'

// interface Branches {
//     karachi: string[]
//     lahore: string[]
//     Islamabad: string[]
// }

export const useBigDataStore = defineStore({
  id: 'bigData',
  state: () => ({
    branches: {
      Karachi: [
        'Federal B Area, Karachi',
        'North Karachi Industrial Area, Karachi',
        'Gulshan-e-Iqbal, Karachi',
        'Karachi Stock Exchange',
        'Marriot Road, Karachi',
        'Defence Karachi (Phase V)',
        'M.A. Jinnah Road, Karachi',
        'Bahadurabad, Karachi',
        'Gulistan-e-Jauhar, Karachi',
        'Paper Market, Karachi',
        'S.I.T.E., Karachi',
        'PECHS, Karachi',
        'Timber Market, Karachi',
        'DHA Phase VII, Khayaban-e-Ittehad Branch, Karachi',
        'Korangi Industrial Area, Karachi',
        'Tipu Sultan Road, Karachi',
        'Jodia Bazar, Karachi',
        'Cloth Market, Karachi',
        'Shahrah-e-Faisal, Karachi',
        'Clifton, Karachi',
        'Hyderi (North Nazimabad), Karachi',
        'Tariq Road, Karachi',
        'Shershah, Karachi',
        'Malir Cantt., Karachi',
        'Gulshan Chowrangi, Karachi',
        'Garden East, Karachi',
        'DHA Phase IV, Karachi',
        'Sea View, Karachi',
        'Nagan Chowrangi, Karachi',
        'Akbar Road, Karachi',
        'Steel Market (New Memon Masjid)',
        'Malir City, Karachi',
        'Khayaban-e-Muslim, DHA, Karachi',
        'Bombay Bazar, Karachi',
        'Khayaban-e-Rahat',
        'DHA Phase II Ext., Karachi',
        'Sharfabad Branch',
        'Beaumont Plaza, Karachi',
        'Block H North Nazimabad',
        'Khayaban-e-Shamsheer, Karachi',
        'Khayaban-e-Shahbaz, Karachi',
        'SIDCO Center, Karachi',
        'Fortune Towers, Shahrah-e-Faisal Branch, Karachi',
        'Main Shahbaz, DHA Branch, Karachi',
        'Schon Circle Branch',
        'KHAYABAN-E-ITTEHAD BRANCH, KARACHI',
        'Head Office Bahria Town',
        'North Napier Road, Karachi',
        'Eidgah, Karachi',
        'Hawksbay Road, Karachi',
        'Ch. Khaliq-uz-Zaman Road (Gizri), Karachi',
        'Saddar, Karachi',
        'Jamshed Road, Karachi',
        'Johar Chowrangi, Karachi',
        'Gulshan-e-Hadeed, Karachi',
        'West Wharf, Karachi',
        'Abul Hasan Ispahani Road, Karachi',
        'Liaquatabad, Karachi',
        'Urdu Bazar, Karachi',
        'Pakistan Chowk, Karachi',
        'Plaza Quarters, Karachi',
        'Khalid Bin Waleed Road',
        'Kawish Crown Plaza Branch',
        'Block F North Nazimabad',
        'Shaheed-e-Millat Road Branch, Karachi',
        'Saba Avenue Branch, DHA Karachi',
        'Safoora Chowrangi Branch',
        'ZAMZAMA COMMERCIAL BRANCH, KARACHI',
        'NISHAT PHASE VI DHA BRANCH, KARACHI',
        'FISH HARBOUR BRANCH, KARACHI',
        'REEF TOWER EMAAR BRANCH, KARACHI',
        'SMCHS, Shahrah-e-Faisal Branch, Karachi',
        'Gulistan-e-Johar, Block 20 Branch, Karachi',
        'Stadium Road KDA Scheme 1 Branch, Karachi',
        'Nazimabad No. 3 Branch, Karachi',
        'Nazimabad Block-B Branch, Karachi',
        'IBG- I.I. Chundrigar Road Karachi',
        'IBG- Shahrah-e-Faisal, Karachi',
        'IBG- Gulshan-e-Iqbal, Karachi',
        'IBG- Gulistan-e-Jauhar, Karachi',
        'IBG- DHA Karachi',
        'IBG- North Nazimabad, Karachi',
        'IBG- SITE - II, Karachi',
        'IBG- Federal B. Area, Karachi',
        'IBG- North Karachi',
        'IBG- Clifton, Karachi',
        'IBG- Nazimabad, Karachi',
        'IBG- Bahadurabad, Karachi',
        'IBG- Bokhari Commercial',
        'IBG- Commercial Area-A Branch DHA Phase II, Karachi',
        'IBG- West Wharf Branch, Karachi',
        'IBG- KDA Office Society Branch, Karachi',
        'IBG- Dolmen Mall Branch, Clifton Karachi',
        'IBG- Saba Avenue Branch, Karachi',
        'IBG- Block-6 PECHS Branch Shahrah-e-Faisal, Karachi',
        'IBG- Korangi Industrial Area, Karachi',
        'IBG- Jodia Bazar, Karachi',
        'IBG- Dhorajee, Karachi',
        'IBG- Orangi Town, Karachi',
        'IBG- Shershah, Karachi',
        'IBG- Shadab Branch',
        'IBG- Paper Market, Karachi',
        'IBG- Allama Iqbal Road Branch, Karachi',
        'IBG- Gulshan Chowrangi Branch, Karachi',
        'IBG- Gulistan-e-Johar Block 3 Branch',
        'IBG- Yaseenabad Branch, Karachi',
        'IBG- Naval Colony Branch',
        'IBG- Muhammad Ali Memorial Cooperative Housing Society (MAMCHS) Branch, Karachi',
        'IBG- Karachi University Branch, Karachi',
        'IBG- Baitus Salam DHA Phase IV Branch, Karachi',
        'CF-Karachi',
        'Corporate - SITE Branch, Karachi',
        'Karachi Main'
      ],
      Lahore: [
        'Shah Alam Market, Lahore',
        'Ravi Road, Lahore',
        'Raiwind Road (Thoker Niaz Beg), Lahore',
        'Urdu Bazar, Lahore',
        'Ferozpur Road, Lahore',
        'Walton Road, Lahore',
        'Ghari Shahu, Lahore',
        'Chuburji, Lahore',
        'Cavalry Ground, Lahore',
        'Main Market Gulberg, Lahore',
        'Montgomery Road, Lahore',
        'DHA Extension, Lahore',
        'Shad Bagh, Lahore',
        'Fortress Stadium, Lahore',
        'Bedian Road, Lahore',
        'EME Society, Lahore',
        'Samanabad, Lahore',
        'Karim Block Allama Iqbal Town, Lahore',
        'Sabzazar Multan Road, Lahore',
        'Fruit Market, Lahore',
        'Link Road Model Town, Lahore',
        'Bahria Town Lahore',
        'Khayaban-e-Iqbal DHA, Lahore',
        'Bata Pur Branch, Lahore',
        'Hall Road Branch, Lahore',
        'State Life Cooperation Housing Society, Lahore',
        'Faisal Town, Lahore',
        'H Block, Gulberg II, Lahore',
        'MM Tower, MM Alam Road Branch, Gulberg II Lahore',
        'DHA Phase 6 Branch, Lahore',
        'DHA Raya Branch, Lahore',
        'Ayubia Market Branch, Lahore',
        'Pechs Valancia Branch, Lahore',
        'LDA Plaza, Lahore',
        'Defence Lahore',
        'Circular Road, Lahore',
        'Township, Lahore',
        'Badami Bagh, Lahore',
        'Allama Iqbal Town, Lahore',
        'Shadman Market, Lahore',
        'Tufail Road (Lahore Cantt.)',
        'Baghbanpura, Lahore',
        'Liberty Market, Lahore',
        'Shahdin Manzil, Lahore',
        'Shahdara, Lahore',
        'Brandreth Road, Lahore',
        'Model Town, Lahore',
        'DHA Phase II, Lahore',
        'Johar Town, Lahore',
        'Wapda Town, Lahore',
        'Mall Road Branch, Lahore',
        'DHA Phase IV, Lahore',
        'Z Block DHA Phase III Branch, Lahore',
        'Lake City, Lahore',
        'DHA Phase 5, Lahore',
        'Lahore Stock Exchange',
        'Azam Cloth Market, Lahore',
        'Zarar Shaheed Road - Guldasht Town, Lahore',
        'Bund Road, Lahore',
        'Ichra, Lahore',
        'Islampura, Lahore',
        'Bilal Gunj Branch, Lahore',
        'People Vehra Shahalam-II Market Branch, Lahore',
        'Dholanwal Branch, Lahore',
        'Chamberlain Circular Road, Lahore',
        'Bahria Safari Branch, Lahore',
        'Harbanspura Branch, Lahore',
        'DHA Phase VIII Branch, Lahore',
        'EME Dha Branch, Lahore',
        'IBG- Gulberg, Lahore',
        'IBG- Y Block, Lahore',
        'IBG- New Garden Town, Lahore',
        'IBG- Johar Town, Lahore',
        'IBG- Izmir Town, Lahore',
        'IBG- McLeod Road, Lahore',
        'IBG- Gulshan-e-Ravi, Lahore',
        'IBG- Zarrar Shaheed Road, Lahore',
        'IBG- Qartaba Chowk, Lahore',
        'IBG- Mughalpura, Lahore',
        'IBG- Multan Road, Lahore',
        'IBG- Wahdat Road, Lahore',
        'IBG- Chung, Lahore',
        'IBG- Chowk Shah Alam, Lahore',
        'IBG- College Road Township, Lahore',
        'IBG- DHA Phase VI, Lahore',
        'IBG- K-Block, Model Town, Lahore',
        'IBG DD Phase IV DHA Branch, Lahore',
        'IBG- Khayaban-e-Jinnah Branch, Lahore',
        'IBG- PIA Housing Society, Lahore',
        'IBG- Q Block DHA, Lahore',
        'IBG- Tech Society, Lahore',
        'IBG- Cavalary Ground Branch, Lahore',
        'IBG- Bahria Town, Lahore',
        'IBG- Allama Iqbal Town, Lahore',
        'IBG- Azam Cloth Market Branch, Lahore',
        'IBG- Daroghawala, Lahore',
        'IBG- Misri Shah Branch, Lahore',
        'IBG- Kahna Nau, Lahore',
        'IBG- Ferozepur Road Branch, Lahore',
        'IBG- Brandreth Road Branch, Lahore',
        'IBG- Tipu Block, New Garden Town Corporate Branch, Lahore',
        'IBG- Jail Road Branch, Lahore',
        'IBG- Paragon City Barki Road Branch, Lahore',
        'CF-Lahore',
        'Gulberg, Lahore'
      ],
      Islamabad: [
        'I-8 Markaz, Islamabad',
        'G-9 Markaz, Islamabad',
        'F-8 Markaz, Islamabad',
        'G-11 Markaz, Islamabad',
        'PWD Branch, Rawalpindi',
        'E-11, Islamabad',
        'F-6 Markaz Branch, Islamabad',
        'Ghauri Town, DHA Phase IV, Islamabad',
        'Jinnah Boulevard, Sector E, DHA-II, Islamabad',
        'Gulberg Greens Branch, Islamabad',
        'Chandi Chowk, Rawalpindi',
        'Ayesha Plaza, Jinnah Avenue, Blue Area - Islamabad Branch',
        'Islamabad Main (Blue Area)',
        'I-10 Markaz, Islamabad',
        'Bhara Kahu, Islamabad',
        'F-11 Markaz, Islamabad',
        'G-7, Islamabad',
        'G-8 Markaz Branch, Islamabad',
        'F-7 Markaz, Islamabad',
        'Stock Exchange Branch, Islamabad',
        'Jinnah Road, Rawalpindi',
        'Chaklala Scheme III, Rawalpindi',
        'Lalazar, Rawalpindi',
        'Peshawar Road, Rawalpindi',
        'Khanna, Rawalpindi',
        'Adamjee Road, Rawalpindi Cantt.',
        'Faizabad, Rawalpindi',
        'Adyala Road, Rawalpindi',
        'Bahria Town Phase IV, Rawalpindi',
        'Bahria Phase 7, Rawalpindi',
        'Lalkurti Branch, Rawalpindi',
        'Mall Rawalpindi [Rawalpindi Main]',
        'Satellite Town, Rawalpindi',
        'Airport Road, Rawalpindi',
        'Bahria Town Phase 8, Rawalpindi',
        'Morgah Branch, Rawalpindi',
        'College Road, Rawalpindi',
        'Chowk Sadiqabad, Rawalpindi',
        'Grain Market, Islamabad',
        'Tench Bhatta, Rawalpindi Cantt.',
        'Baghsardaran, Rawalpindi',
        'Naz Cinema Murree Road, Rawalpindi',
        'Bohar Bazar, Rawalpindi',
        'Liaquat Road, Rawalpindi',
        'DHA Phase II Branch, Islamabad',
        'Tarlai Khan, Islamabad',
        'Pirwadhai Branch, Rawalpindi',
        'D-12 Markaz Branch, Islamabad',
        'Top City Branch, Islamabad',
        'Syed Gold Mall Sub Branch, Rawalpindi',
        'IBG - Jinnah Avenue, Blue Area, Islamabad',
        'IBG - G-10 Markaz, Islamabad',
        'IBG - I-9 Markaz, Islamabad',
        'IBG - DHA Phase II, Islamabad',
        'IBG - Bahria Town Branch, Islamabad',
        'IBG - F-8 Markaz, Islamabad',
        'IBG - F-7 Markaz Branch, Islamabad',
        'IBG - E-II, Islamabad',
        'IBG - F-10 Markaz, Islamabad',
        'IBG - G-15/F-15 Khayaban-e-Kashmir Branch, Islamabad',
        'IBG - F-6 Markaz Branch, Islamabad',
        'IBG - Bahria Enclave Branch, Islamabad',
        'IBG - Murree Road, Rawalpindi Cantt.',
        'IBG - Satellite Town, Rawalpindi',
        'IBG - Khayaban-e-Sir Syed, Rawalpindi',
        'IBG - Hamilton, Rawalpindi',
        'IBG - Bahria Town Phase IV, Rawalpindi',
        'IBG - Bahria Town Phase 8, Rawalpindi',
        'IBG - Kalma Chowk, Rawalpindi',
        'IBG - G-13, Islamabad',
        'IBG - Afshan Colony Branch, Rawalpindi',
        'IBG - Committee Chowk, Rawalpindi',
        'IBG - Aabpara Branch, Islamabad',
        'Wah Cantt',
        'Kallar Syedan',
        'CF - Islamabad',
        'F-10 Markaz, Islamabad'
      ],
      Faisalabad: [
        'Peoples Colony, Faisalabad',
        'Minerva Road, Faisalabad',
        'Susan Road, Faisalabad',
        'Rail Bazar, Faisalabad',
        'Yarn Market, Faisalabad',
        'Samanabad, Faisalabad',
        'IBG- Kutchery Bazar, Faisalabad',
        'IBG- Medical College Road PMC, Faisalabad',
        'IBG- Satyana Road, Faisalabad',
        'IBG- Chak No. 204 RB  [Canal Road], Faisalabad',
        'Ghulam Muhammad Abad Branch, Faisalabad'
      ],
      Multan: [
        'Abdali Road, Multan [Multan Main]',
        'Vehari Road',
        'Hussain Agahi, Multan',
        'Shah Rukn-e-Alam, Multan',
        'Bosan Road, Multan',
        'Quaid-e-Azam Road, Multan Cantt',
        'Tipu Sultan Road Multan, Cantt',
        'IBG- Bosan Road, Multan',
        'IBG- Buch Villas Branch, Multan'
      ]
    } as any
  }),
  actions: {
    login() {
      console.log('login from store')
    }
  }
})
